### ISSUE TITLE
Release a new version of PGA, updated, fixed, including stars

### ISSUE THREAD

**Issue by jfontan** [src-d/datasets#107]
This is an umbrella issue to download a new version of PGA.

* [x] PGA create improvements
  * [x] Add stars to index file #43
  * [x] Add repository size to index #17
  * [x] Support selecting version in pga downloader #108
* [x] Release new borges with fixes
  * [x] Close queue.JobIter on error and set Queue Notifier src-d/borges#383
  * [x] Upgrade go-git to fix locked push goroutines src-d/borges#384
* [ ] Sync and plan with infrastructure to deploy PGA download
  * [x] Create k8s batch jobs to automate as much as possible
  * [ ] Document the process for next updates
* [x] Download repositories src-d/datasets#117
* [x] Index repositories src-d/datasets#118
* [x] Get new servers that can host multiple PGA versions
* [x] Upload new version to to web server

**Comment by EgorBu** [comment]
Great idea!

How about adding language statistics?
Percentages per languages (`enry --breakdown`) - so people can select not only repositories with at least 1 line of code in a specific language but have more advanced options for filtering.

**Comment by jfontan** [comment]
@EgorBu We want to have this as soon as possible and automate what we can. Adding more features is not a priority right now. We will start thinking on new features after we are able to update PGA in a semi automated way.

Can you open an issue to don't forget it for the next iteration?

**Comment by EgorBu** [comment]
@jfontan, thank you! Here's https://github.com/src-d/datasets/issues/110

**Comment by vmarkovtsev** [comment]
@jfontan I guess that this is done.

**Comment by jfontan** [comment]
Documentation is still not done but I believe it's not needed now that borges is phased out. Closing. Thanks for the heads up.
