### ISSUE TITLE
Missing repositories to process

### ISSUE THREAD

**Issue by erizocosmico** [src-d/datasets#12]
This is the list of the _currently_ missing repositories from the latest 181k repos index. This is due to corrupted siva files (or any other issue that may have arised) and we should reprocess (and redownload) them again.

Here's the list: https://gist.github.com/erizocosmico/1dfa3bc5e1d04ba2f15266ab4493420e

Borges is processing the last 4k repos, so I'm posting this here so we don't forget to do it later after it's done.

### Tasks

- [x] Add corrupted siva files repos to the queue
- [x] Add flag to borges-indexer to generate an index only for a list of repositories
- [x] Redownload the repos in the list
- [x] Process the list to generate an index
- [x] Join with latest index and set forks
